# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self
 

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ecc424de-7c84-4641-930b-9ec25bddf17b'
  imageRepository: 'dotnet6docker'
  containerRegistry: 'mybflcontainer.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  
  tag: '$(Build.BuildId)'
  workingDirectory: '$(Build.SourcesDirectory)/Admin_Projects'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        buildContext: '$(Build.Repository.LocalPath)'
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        
        tags: |
          $(tag)
        
